//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repertoar.App_GlobalResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Repertoar.App_GlobalResourses.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En kompositör måste väljas. .
        /// </summary>
        internal static string Action_Required {
            get {
                return ResourceManager.GetString("Action_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låten togs bort..
        /// </summary>
        internal static string Action_Song_Deleted {
            get {
                return ResourceManager.GetString("Action_Song_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låten sparades..
        /// </summary>
        internal static string Action_Song_Saved {
            get {
                return ResourceManager.GetString("Action_Song_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låten uppdaterades..
        /// </summary>
        internal static string Action_Song_Updated {
            get {
                return ResourceManager.GetString("Action_Song_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffade när låten skulle tas bort..
        /// </summary>
        internal static string Song_Deleting_Error {
            get {
                return ResourceManager.GetString("Song_Deleting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då låten skulle läggas till..
        /// </summary>
        internal static string Song_Inserting_Error {
            get {
                return ResourceManager.GetString("Song_Inserting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel intäffade då låten skulle läggas till/uppdateras..
        /// </summary>
        internal static string Song_Inserting_Error_IU {
            get {
                return ResourceManager.GetString("Song_Inserting_Error_IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel intäffade då låten skulle läggas uppdateras..
        /// </summary>
        internal static string Song_Inserting_Error_U {
            get {
                return ResourceManager.GetString("Song_Inserting_Error_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låten med nummer {0} hittades inte..
        /// </summary>
        internal static string Song_Not_Found {
            get {
                return ResourceManager.GetString("Song_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel inträffade då låten hämtades vid redigering..
        /// </summary>
        internal static string Song_Selecting_Error {
            get {
                return ResourceManager.GetString("Song_Selecting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då låten skulle uppdateras..
        /// </summary>
        internal static string Song_Updating_Error {
            get {
                return ResourceManager.GetString("Song_Updating_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låtnamn måste anges..
        /// </summary>
        internal static string Song_Value_Required {
            get {
                return ResourceManager.GetString("Song_Value_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel inträffade. Korrigera det som är fel och försök igen..
        /// </summary>
        internal static string Validation_Header {
            get {
                return ResourceManager.GetString("Validation_Header", resourceCulture);
            }
        }
    }
}
